var loggedInOut = false; 
var homeContent = `<h1>Purple</h1> <p>Purple is a color similar in appearance to violet light. In the RYB color model historically used in the arts, purple is a secondary color created by combining red and blue pigments in different proportions. In the CMYK color model used in modern printing, purple is made by combining magenta pigment with either cyan pigment, black pigment, or both. In the RGB color model used in computer and television screens, purple is created by mixing red and blue light in order to create colors that appear similar to violet light.</p> <p>Below is several images demonstrating the color purple, from left to right they are: a field of purple flowers, and an amethyst, a sunset whom's lighting makes the mountains look purple, and an African violet-backed starling.</p> <div style="text-align:center;"> <img src="images/Campanula-carpatica-Rapido-Blue-2-1080x1080-1-1024x1024.jpg" width="300px"> <img src="images/Amatista_Laye_2.jpg" width="300px"> <img src="images/Auke_Bay_Alaska_2.jpg" width="300px"> <img src="images/Cinnyricinclus_leucogaster_-_20080321.jpg" width="300px"> </div> <p>The color purple is visibly similar to the color violet. Violet is the color of light at the short wavelength end of the visible spectrum, between blue and invisible ultraviolet. It is one of the seven colors that Isaac Newton labeled when dividing the spectrum of visible light in 1672. Violet light has a wavelength between approximately 380 and 435 nanometers. The color's name is derived from the violet flower.</p>`
var aboutContent = `<h1>About</h1> <p>Purple first appeared in prehistoric art during the Neolithic era. The artists of Pech Merle cave and other Neolithic sites in France used sticks of manganese and hematite powder to draw and paint animals and the outlines of their own hands on the walls of their caves. These works have been dated to between 16,000 and 25,000 BC.</p> <p>As early as the 15th century BC the citizens of Sidon and Tyre, two cities on the coast of Ancient Phoenicia (present day Lebanon), were producing purple dye from a sea snail called the spiny dye-murex. Clothing colored with the Tyrian dye was mentioned in both the Iliad of Homer and the Aeneid of Virgil. The deep, rich purple dye made from this snail became known as Tyrian purple.</p> <img src="images/Mosaic_of_Justinianus_I_-_Basilica_San_Vitale_(Ravenna).jpg" width="200px" text-align="center"> <p>The process of making the dye was long, difficult and expensive. Thousands of the tiny snails had to be found, their shells cracked, the snail removed. Mountains of empty shells have been found at the ancient sites of Sidon and Tyre. The snails were left to soak, then a tiny gland was removed and the juice extracted and put in a basin, which was placed in the sunlight. There, a remarkable transformation took place. In the sunlight the juice turned white, then yellow-green, then green, then violet, then a red which turned darker and darker. The process had to be stopped at exactly the right time to obtain the desired color, which could range from a bright crimson to a dark purple, the color of dried blood. Then either wool, linen or silk would be dyed. The exact hue varied between crimson and violet, but it was always rich, bright and lasting</p>`
var productsContent = `<h1>Products</h1> <p>Below are examples of our eco-friendly reusable water bottles that come in various shades of purple</p> <div style="text-align:center;"> <img src="images/Built-20-Ounce-Pivot-Double-Wall-Stainless-Steel-Bottle-20-Ounce-Purple_cd9b2b43-ccb8-47d4-8fef-258127436ed0.32f8491c995436681467f18beaa19407.webp" width="400px"><img src="images/SS-CY0002-006-P1__63542.jpg" width="400px"><img src="images/ss-water-bottle-purple-be-still.jpg" width="400px"> <br><br> <span style="background-color:#400080; color:#FFF; padding:20px; border-radius:25%; width:40px;">Buy now!</span></div>`
var contactContent = `<h1>Contact</h1> <p>Have questions or concerns? Use the form below to send us a message.</p> <label>Name: </label><input type="text" placeholder="John Smith..."> <label>E-mail: </label><input type="text" placeholder="example@website.com"> <label>Phone number: </label><input type="number" placeholder="(000)-000-0000"> <br><br> <label>Comment: </label> <input type="text" placeholder="Text..." style="width:70%;"> <h1>Donate</h1> <p>Have questions or concerns? Use the form below to send us a message.</p> <label>Name: </label><input type="text" placeholder="John Smith..."> <label>E-mail: </label><input type="text" placeholder="example@website.com"> <label>Donation amount: </label><input type="number" placeholder="$0"><br><br><br><div style="text-align:center"><img src="images/Color_icon_purple_v2.svg.png" width="400px"></div>`

export function addPageContent(pageName){
    let pageContentName = pageName + "Content";
    $(".app").html(eval(pageContentName));
}

export function setLoggedInOut(){
    if(loggedInOut == true){
        loggedInOut = false;
        $("nav .links .log span").html("Log In")
    }else{
        loggedInOut = true;
        $("nav .links .log span").html("Log Out")
    }
   }


export function getLoggedInOut(){
    return loggedInOut;
}